Repository UIverse-Team/UIverse-FE, pull requests merged in 2025-04, with the labels that each got.

#176 [design] 마이페이지 홈 퀵메뉴 링크 연결, 특정 메뉴 count 삭제
  src/app/(mypage)/mypage/page.tsx
  src/components/login/MemberLogin.tsx
Labels: design

#185 [refact] 아코디언 컴포넌트 리팩토링
  src/components/common/Accordion/Accordion.tsx
  src/components/keyword/RealTimeProductComponent.tsx
  src/components/product/RealTimeAccordion.tsx
  src/mocks/accordionData/accordionData.ts
  src/types/realTimeKeyword/realTimeKeywordType.ts
Labels: refact

#187 [fix] 주문상세조회 API 변경 반영
  src/app/(mypage)/orders/[orderNumber]/page.tsx
  src/components/order/OrderWrap.tsx
  src/services/orderService.server.ts
  src/services/orderService.ts
Labels: fix

#193 [design] tap metadata 설정
  src/app/layout.tsx
Labels: design

#192 [feature] 상품 검색 결과 페이지 구현
  public/home-banner.jpg
  src/app/(mypage)/mypage/page.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/banner/EventBanner.tsx
  src/components/common/CardProduct/CardProduct.tsx
  src/components/common/Redirect/Redirect.tsx
  src/components/keyword/RealTimeProductComponent.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/SearchBar/SearchBar.tsx
  src/components/mypage/UserName.tsx
  src/components/search/ProductSection.tsx
  src/components/search/SearchContainer.tsx
  src/components/search/SearchHeader.tsx
  src/components/search/StoreCard.tsx
  src/components/search/StoreSection.tsx
  src/constants/prouctSortParams.ts
  src/constants/queryKeys.ts
  src/constants/routes.ts
  src/hooks/useSearch.ts
  src/services/productService.server.ts
  src/services/productService.ts
  src/types/Product/productsType.ts
  src/types/store/storeTypes.ts
Labels: design, feature

#200 fix: 주문목록에서 제품 클릭시 제품 상세 페이지 연결 수정
  src/app/best/layout.tsx
  src/app/best/page.tsx
  src/app/sale/layout.tsx
  src/app/sale/page.tsx
  src/components/order/OrderListCard.tsx
Labels: fix

#201 [design] 마이페이지 홈 사용자 이름 설정, 목데이터 변경
  src/app/(mypage)/mypage/page.tsx
  src/components/mypage/UserName.tsx
Labels: design

#190 [feature] 비회원 주문조회 페이지 기능 구현
  src/app/guest/[orderNumber]/page.tsx
  src/components/auth/login/GuestOrderCheck.tsx
  src/services/orderService.server.ts
  src/services/orderService.ts
Labels: feature

#203 [fix] readme 수정
  README.md
  next.config.ts
  src/app/purchase-complete/OrderComplete.tsx
  src/components/cart/CartHeader.tsx
  src/components/common/Input/Input.tsx
  src/components/product/AllProducts.tsx
  src/components/product/WishProductLists.tsx
  src/components/purchase/PurchaseForm.tsx
  src/components/purchase/PurchaseShoppingInfo.tsx
  src/services/purchaseService.ts
  src/util/formatPhoneNumber.ts
Labels: fix, docs

#204 [docs] readme에 roadmap 추가
  README.md
Labels: docs

#206 [fix] product 안쓰는 타입 제거 및 productService 수정
  src/services/productService.ts
  src/types/Product/productsType.ts
Labels: fix

#210 fix: 장바구니 회원 비회원 수량 관리
  README.md
  src/app/api/[...path]/route.ts
  src/app/api/carts/route.ts
  src/app/api/ordersGuest/route.ts
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemList.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartPayForm.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/product/CartWishlistButtons.tsx
  src/components/product/QuantitySelector.tsx
  src/components/purchase/PurchaseForm.tsx
  src/components/purchase/PurchaseProductsItemList.tsx
  src/hooks/useCart.tsx
  src/mocks/handlers.js
  src/services/purchaseService.ts
  src/stores/productStore.ts
Labels: fix

#217 feature: 상품 옵션에 따른 구매 기능 추가
  src/app/api/product/[id]/route.ts
  src/app/product/[productId]/page.tsx
  src/app/purchase/page.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/product/CartWishlistButtons.tsx
  src/components/product/ProductColorOptionList.tsx
  src/components/product/ProductOptionLists.tsx
  src/components/product/ProductSizeOptionList.tsx
  src/components/product/QuantitySelector.tsx
  src/stores/productStore.ts
  src/types/Product/productDetailType.ts
  src/util/formatDate.ts
Labels: feature

#215 [design] 회원정보수정 마크업
  src/app/(mypage)/edit-profile/page.tsx
  src/components/auth/edit-profile/AdAlertSetting.tsx
  src/components/auth/edit-profile/Addresses.tsx
  src/components/auth/edit-profile/EditProfile.tsx
Labels: design

#224 feature: 상품 옵션에 따른 구매 기능 구현(회원,비회원 바로구매,장바구니)
  src/app/product/[productId]/page.tsx
  src/app/purchase/page.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/product/CartWishlistButtons.tsx
  src/components/product/ProductColorOptionList.tsx
  src/components/product/ProductOptionLists.tsx
  src/components/product/ProductSizeOptionList.tsx
  src/components/product/QuantitySelector.tsx
  src/components/purchase/PurchaseForm.tsx
  src/components/purchase/PurchaseProductsList.tsx
  src/hooks/useCart.tsx
  src/services/cartService.ts
  src/services/purchaseService.ts
  src/stores/productStore.ts
  src/types/Product/productDetailType.ts
Labels: feature

#227 feature: 회원 장바구니 완료
  src/app/api/carts/route.ts
  src/services/cartService.ts
  src/types/cart/cartType.ts
Labels: feature

#226 [feature] 리뷰 작성 기능 구현
  next.config.ts
  public/icons/delete-circle.svg
  public/icons/left-arrow.svg
  public/icons/plus-circle.svg
  public/icons/review-complete.svg
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/reviews/complete/layout.tsx
  src/app/(mypage)/reviews/complete/page.tsx
  src/app/(mypage)/reviews/register/layout.tsx
  src/app/(mypage)/reviews/register/page.tsx
  src/app/api/uploadFile/route.ts
  src/app/purchase-complete/OrderComplete.tsx
  src/components/common/BackButton/BackButton.tsx
  src/components/common/BodyStyleController.ts
  src/components/common/rating/StarRating.tsx
  src/components/common/rating/StarRatingInput.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/order/OrderListCard.tsx
  src/components/order/OrderWrap.tsx
  src/components/order/WriteReviewModal.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/reviewComplete/ReviewCompleteContent.tsx
  src/components/review/reviewForm/CustomModal.tsx
  src/components/review/reviewForm/ReviewContent.tsx
  src/components/review/reviewForm/ReviewForm.tsx
  src/components/review/reviewForm/ReviewImage.tsx
  src/components/review/reviewForm/ReviewRating.tsx
  src/components/review/reviewForm/ReviewTag.tsx
  src/constants/queryKeys.ts
  src/constants/reviewTag.ts
  src/constants/routes.ts
  src/hooks/useReviewForm.ts
  src/libs/axios/apiMethods.ts
  src/mocks/reviewMain/reviewData.ts
  src/services/fileService.ts
  src/services/orderService.server.ts
  src/services/orderService.ts
  src/services/reviewService.server.ts
  src/services/reviewService.ts
  src/types/Product/productsType.ts
  src/types/review/reviewType.ts
Labels: design, feature
