Repository UIverse-Team/UIverse-FE, pull requests merged in 2025-03, with the labels that each got.

#76 feature: 비회원, 회원 장바구니 기능 구현 완료
  src/app/api/carts/[id]/route.ts
  src/app/api/carts/guest/route.ts
  src/app/api/carts/route.ts
  src/app/api/guestcarts/[id]/route.ts
  src/app/api/guestcarts/route.ts
  src/app/cart/page.tsx
  src/app/product/[id]/page.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemActions.tsx
  src/components/cart/CartItemForm.tsx
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemList.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartPayForm.tsx
  src/components/cart/CartProductList.tsx
  src/components/cart/EmptyCartMessage.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/product/CartWishlistButtons.tsx
  src/hooks/useCart.tsx
  src/services/cartService.ts
  src/types/cart/cartType.ts
  src/util/httpClient.ts
Labels: feature

#78 [feature] 상태에 따른 헤더 컴포넌트 기능 구현
  public/icons/Delete.svg
  public/icons/clock.svg
  public/icons/popular.svg
  public/icons/recommend-search.svg
  src/app/(main)/page.tsx
  src/components/common/Chip/Chip.tsx
  src/components/common/Dialog/Dialog.tsx
  src/components/common/ViewportAdjuster.ts
  src/components/design-system/ChipTest.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/SearchBar.tsx
  src/components/layout/Header/SearchBar/KeywordList.tsx
  src/components/layout/Header/SearchBar/RecentSearchList.tsx
  src/components/layout/Header/SearchBar/SearchBar.tsx
  src/components/layout/Header/SearchBar/SearchDropdown.tsx
  src/components/layout/Header/SearchBar/SuggestionList.tsx
  src/constants/index.ts
  src/constants/localStorageKey.ts
  src/constants/menu.ts
  src/constants/menuItems.ts
  src/constants/routes.ts
  src/hooks/useSearch.ts
  src/util/localstorageUtil.ts
Labels: feature

#82 [setting] tanstack query 설정
  package.json
  src/app/layout.tsx
  src/components/common/Breadcrumb/Breadcrumb.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/TextButton.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Divider/Divider.tsx
  src/components/common/HelperLabel/HelperLabel.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Radio/RadioGroup.tsx
  src/components/common/Radio/RadioGroupItem.tsx
  src/components/common/Tab/Tab.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/ui/PagationContainer.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/select.tsx
  src/constants/queryKeys.ts
  src/hooks/useDataMutation.ts
  src/hooks/useFetchData.ts
  src/lib/utils.ts
  src/libs/tailwindcss/utils.ts
  src/libs/tanstackQuery/PrefetchedQueryHydrationBoundary.tsx
  src/libs/tanstackQuery/QueryClientProvider.tsx
  src/libs/tanstackQuery/queryClient.ts
  src/providers/Providers.tsx
  yarn.lock
Labels: feature, setting

#83 [refact] 타입 추가에 따른 리팩토링 및 컴포넌트명 통일
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/cart/layout.tsx
  src/app/product/[id]/layout.tsx
  src/app/product/[id]/page.tsx
  src/components/layout/Container/Container.tsx
  src/components/signup/AgreementForm.tsx
  src/components/signup/EmailForm.tsx
  src/components/signup/PasswordForm.tsx
  src/components/signup/UserInfoForm.tsx
  src/types/container/containerType.ts
  src/types/multistep/multistep.ts
Labels: refact

#99 feature: HydrationBoundary, api, reactQuery, api 분리
  src/app/product/[id]/page.tsx
  src/app/product/[productId]/layout.tsx
  src/app/product/[productId]/page.tsx
  src/components/cart/CartItemForm.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/product/CartWishlistButtons.tsx
  src/components/product/ProductInfo.tsx
  src/components/product/ProductMainImage.tsx
  src/components/product/ProductReadMore.tsx
  src/components/product/ProductTabs.tsx
  src/components/product/QuantitySelector.tsx
  src/constants/queryKeys.ts
  src/services/productService.ts
  src/stores/productStore.ts
Labels: feature

#104 [feature] 아이디 찾기 기능 1차 구현
  .env.dev
  package.json
  public/icons/clipboard.svg
  src/app/(auth)/find-id/layout.tsx
  src/app/(auth)/find-id/page.tsx
  src/app/product/[productId]/page.tsx
  src/components/findAccount/findId/FindIdComplete.tsx
  src/components/findAccount/findId/FindIdForm.tsx
  src/components/signup/EmailForm.tsx
  src/constants/queryKeys.ts
  src/constants/routes.ts
  src/hooks/usePhoneVerification.ts
  src/serverActions/auth/findId/actions.ts
  src/util/formatPhoneNumber.ts
  src/util/httpClient.ts
  yarn.lock
Labels: design, feature

#105 [feature] 아이디찾기 구현
  src/app/(auth)/find-id/page.tsx
  src/app/layout.tsx
  src/components/findAccount/findId/FindIdComplete.tsx
  src/components/findAccount/findId/FindIdForm.tsx
  src/hooks/usePhoneVerification.ts
  src/serverActions/auth/findId/actions.ts
  src/util/httpClient.ts
Labels: design, feature

#106 feature: 장바구니 기능 및 상품 상세 디자인, api 수정, 챗봇 추가
  public/icons/chevron.svg
  src/app/(main)/page.tsx
  src/app/api/carts/guest/route.ts
  src/app/api/carts/route.ts
  src/app/api/product/[id]/route.ts
  src/app/api/products/popular/route.ts
  src/app/api/products/route.ts
  src/app/cart/loading.tsx
  src/app/product/[productId]/page.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartInformation.tsx
  src/components/cart/CartItem.tsx
  src/components/cart/CartItemActions.tsx
  src/components/cart/CartItemForm.tsx
  src/components/cart/CartItemHeader.tsx
  src/components/cart/CartItemList.tsx
  src/components/cart/CartList.tsx
  src/components/cart/CartPayForm.tsx
  src/components/cart/CartProductList.tsx
  src/components/cart/EmptyCartMessage.tsx
  src/components/common/NumbericField/NumbericField.tsx
  src/components/common/rating/StarRating.tsx
  src/components/product/AllProducts.tsx
  src/components/product/ProductBreadCrumbConainer.tsx
  src/components/product/ProductInfo.tsx
  src/components/product/ProductMainImage.tsx
  src/components/product/ProductReadMore.tsx
  src/components/product/ProductTabs.tsx
  src/constants/queryKeys.ts
  src/hooks/useCart.tsx
  src/hooks/useFetchData.ts
  src/services/cartService.ts
  src/services/productService.ts
  src/stores/productScrollLocationStore.ts
  src/types/Product/productDetailType.ts
  src/types/Product/productsType.ts
Labels: feature

#112 [refact] 휴대폰인증 서버액션 파일 위치 수정
  src/app/(auth)/find-pw/layout.tsx
  src/app/(auth)/find-pw/page.tsx
  src/components/findAccount/findPw/ChangePwForm.tsx
  src/components/findAccount/findPw/FindPwComplete.tsx
  src/components/findAccount/findPw/FindPwForm.tsx
  src/hooks/useMultiStepForm.ts
  src/hooks/usePhoneVerification.ts
  src/serverActions/auth/phoneVerify/actions.ts
Labels: refact

#114 [feature] 회원가입 기능 구현
  src/app/(auth)/signup/page.tsx
  src/components/common/Input/Input.tsx
  src/components/login/MemberLogin.tsx
  src/components/signup/AgreementForm.tsx
  src/components/signup/EmailForm.tsx
  src/components/signup/PasswordForm.tsx
  src/components/signup/SignUpComplete.tsx
  src/components/signup/UserInfoForm.tsx
  src/hooks/useMultiStepForm.ts
  src/mocks/handlers.js
  src/serverActions/auth/phoneVerify/actions.ts
  src/serverActions/auth/signup/actions.ts
  src/types/signup/signupType.ts
Labels: feature

#116 design: toast 공통 컴포넌트 만들기
  package.json
  public/icons/info-circle.svg
  src/app/layout.tsx
  src/components/common/Toast/Toast.tsx
  src/components/product/ProductInfo.tsx
  src/components/ui/sonner.tsx
  yarn.lock
Labels: design

#121 [feature] 소셜 로그인 기능 구현
  package.json
  src/components/auth/login/SocialLogin.tsx
  src/components/layout/Header/Header.tsx
  src/middleware.ts
  src/serverActions/auth/login/actions.ts
  src/store/user.ts
  src/types/login/loginType.ts
  src/types/routes/routesType.ts
  yarn.lock
Labels: feature

#124 [feature] 비밀번호 찾기 구현
  package.json
  src/app/(auth)/find-pw/page.tsx
  src/components/findAccount/findId/FindIdForm.tsx
  src/components/findAccount/findPw/ChangePwForm.tsx
  src/components/findAccount/findPw/FindPwForm.tsx
  src/components/signup/EmailForm.tsx
  src/components/signup/UserInfoForm.tsx
  src/hooks/useEmailVerification.ts
  src/hooks/usePasswordChange.ts
  src/hooks/usePhoneVerification.ts
  src/serverActions/auth/emailVerify/actions.ts
  src/serverActions/auth/findId/actions.ts
  src/serverActions/auth/findPw/actions.ts
  src/serverActions/auth/phoneVerify/actions.ts
  src/serverActions/auth/signup/actions.ts
  src/types/emailVerify/emailType.ts
  src/types/serverAction/serverActionType.ts
  yarn.lock
Labels: design, feature

#129 [feature] 마이페이지 관련 페이지 세팅
  src/app/faq/layout.tsx
  src/app/faq/page.tsx
  src/app/favorites/layout.tsx
  src/app/favorites/page.tsx
  src/app/inquiry/layout.tsx
  src/app/inquiry/page.tsx
  src/app/mypage/custom/layout.tsx
  src/app/mypage/custom/page.tsx
  src/app/mypage/edit-profile/layout.tsx
  src/app/mypage/edit-profile/page.tsx
  src/app/mypage/page.tsx
  src/app/notice/layout.tsx
  src/app/notice/page.tsx
  src/app/orders/layout.tsx
  src/app/orders/page.tsx
  src/app/recent-views/layout.tsx
  src/app/recent-views/page.tsx
  src/app/restock-alerts/layout.tsx
  src/app/restock-alerts/page.tsx
  src/app/reviews/layout.tsx
  src/app/reviews/page.tsx
  src/constants/routes.ts
  src/middleware.ts
Labels: feature

#137 [fix] 인증인가 관련 에러 해결
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/login/GuestOrderCheck.tsx
  src/components/auth/login/MemberLogin.tsx
  src/components/auth/login/SocialLogin.tsx
  src/components/auth/signup/AgreementForm.tsx
  src/components/auth/signup/EmailForm.tsx
  src/components/auth/signup/PasswordForm.tsx
  src/components/auth/signup/SignUpComplete.tsx
  src/components/auth/signup/UserInfoForm.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/components/layout/Header/Header.tsx
  src/components/login/MemberLogin.tsx
  src/serverActions/auth/login/actions.ts
  src/serverActions/auth/logout/actions.ts
  src/store/user.ts
  src/stores/user.ts
Labels: fix

#138 feature: 메인 페이지 작업 완료 (백엔드 기능 미완으로 mock 데이터 사용)
  public/icons/binocular.svg
  public/icons/chat.svg
  src/app/(main)/page.tsx
  src/components/common/Accordion/Accordion.tsx
  src/components/keyword/RealTimeProductCard.tsx
  src/components/keyword/RealTimeProductComponent.tsx
  src/components/product/AllProducts.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewMainComponent.tsx
  src/components/special-price/SpecialPrice.tsx
  src/components/wish-products/WishProduct.tsx
  src/mocks/accordionData/accordionData.ts
  src/mocks/reviewMain/reviewData.ts
  src/services/realTimeService.ts
  src/types/realTimeKeyword/realTimeKeywordType.ts
  src/types/review/reviewType.ts
  src/util/getTodayDate.ts
Labels: feature

#140 [fix] zustand persist hydrantion delete
  src/stores/user.ts
Labels: fix

#142 [feature] 헤더 햄버거 메뉴 기능 구현
  src/app/(main)/layout.tsx
  src/components/banner/EventBanner.tsx
  src/components/layout/Container/Container.tsx
  src/components/layout/Header/HamburgerMenu.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/MenuNavList.tsx
  src/types/container/containerType.ts
Labels: design, feature

#153 [design] 주문 목록 페이지 마크업
  public/icons/chevron-down.svg
  src/app/(mypage)/custom/layout.tsx
  src/app/(mypage)/custom/page.tsx
  src/app/(mypage)/edit-profile/layout.tsx
  src/app/(mypage)/edit-profile/page.tsx
  src/app/(mypage)/faq/layout.tsx
  src/app/(mypage)/faq/page.tsx
  src/app/(mypage)/favorites/layout.tsx
  src/app/(mypage)/favorites/page.tsx
  src/app/(mypage)/inquiry/layout.tsx
  src/app/(mypage)/inquiry/page.tsx
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/mypage/layout.tsx
  src/app/(mypage)/mypage/page.tsx
  src/app/(mypage)/notice/layout.tsx
  src/app/(mypage)/notice/page.tsx
  src/app/(mypage)/orders/layout.tsx
  src/app/(mypage)/orders/page.tsx
  src/app/(mypage)/recent-views/layout.tsx
  src/app/(mypage)/recent-views/page.tsx
  src/app/(mypage)/restock-alerts/layout.tsx
  src/app/(mypage)/restock-alerts/page.tsx
  src/app/(mypage)/reviews/layout.tsx
  src/app/(mypage)/reviews/page.tsx
  src/app/mypage/page.tsx
  src/app/orders/page.tsx
  src/components/auth/login/GuestOrderCheck.tsx
  src/components/auth/signup/SignUpComplete.tsx
  src/components/common/Select/Select.tsx
  src/components/layout/Container/Container.tsx
  src/components/layout/Header/Header.tsx
  src/components/login/MemberLogin.tsx
  src/components/order/Order.tsx
  src/components/order/OrderListCard.tsx
  src/constants/routes.ts
  src/middleware.ts
  src/types/container/containerType.ts
Labels: design

#152 [fix] 로그인 후 1시간이 지나서 인증토큰이 만료된 상태여도 zustand 설정이 바뀌지 않는 오류 해결
  src/components/auth/login/MemberLogin.tsx
  src/components/layout/Header/Header.tsx
  src/constants/routes.ts
  src/middleware.ts
  src/serverActions/auth/logout/actions.ts
  src/stores/user.ts
Labels: fix

#163 [fix] dialog에 x 버튼 옵션 추가
  src/components/auth/signup/AgreementForm.tsx
  src/components/common/Dialog/Dialog.tsx
  yarn.lock
Labels: fix

#165 [design] 목데이터 기반 주문 목록 조회 마크업
  src/app/(mypage)/layout.tsx
  src/app/(mypage)/orders/[id]/page.tsx
  src/app/(mypage)/orders/page.tsx
  src/components/auth/signup/AgreementForm.tsx
  src/components/order/ExchangeReturnModal.tsx
  src/components/order/Order.tsx
  src/components/order/OrderListCard.tsx
  src/components/order/OrderWrap.tsx
  src/components/order/TrackingModal.tsx
  src/components/order/WriteReviewModal.tsx
Labels: design

#166 design: 스켈레톤 메인 페이지, 장바구니 상품 리스트 완료
  src/app/(main)/page.tsx
  src/app/api/products/popular/route.ts
  src/app/purchase/page.tsx
  src/components/cart/CartItemForm.tsx
  src/components/cart/CartProductList.tsx
  src/components/cart/CartProductListSkeleton.tsx
  src/components/product/AllProductSkeleton.tsx
  src/components/product/AllProducts.tsx
  src/components/purchase/PurchaseProductsList.tsx
  src/components/purchase/PurchaseProductsListSkeleton.tsx
  src/components/ui/skeleton.tsx
  src/constants/queryKeys.ts
  src/services/productService.ts
Labels: design
